# Introducción a  Numpy

Uno de los módulos más importantes de Python es **[Numpy](http://www.numpy.org/)**.

Numpy es el encargado de añadir toda la capacidad matemática y vectorial a Python haciendo posible operar con cualquier dato numérico o array (posteriormente veremos qué es un array).

## ¿Porqué usar Numpy?

En múltiples ocasiones necesitamos hacer operaciones numéricas sobre datos provenientes de archivos Excel o Bases de datos que contienen múltiples campos (columnas) y múltiples registros (filas).

Vimos que en Python existen las listas, tuplas y diccionarios, las cuales son de gran ayuda para almacenar y administrar datos. Veamos qué sucede cuando queremos sumar los elementos almacenados en dos listas.

In [1]:
x=[1,2,3,4]
y=[5,6,7,8]
print(x+y)

[1, 2, 3, 4, 5, 6, 7, 8]


Como podemos notar, el operador + simplemente concatena las dos listas.
Pero ... ¿Cómo haríamos para sumar los elementos de las dos listas, elemento por elemento?

In [2]:
suma=[]
for i in range(4):
    suma.append(x[i]+y[i])
    
print(suma)

[6, 8, 10, 12]


## Cómo importar el paquete Numpy

Partimos importando el paquete numpy usando la función import. En este caso usaremos el alias np para referirnos de manera más abreviada a las clases y  métodos implementados en numpy.

In [3]:
import numpy

In [4]:
import numpy as np
print(np.__version__)

1.13.3


In [5]:
help(np)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



## Definición de arreglos en Numpy

In [6]:
# Definir un arreglo 1D

x = np.array([1,2,3,4])
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[1 2 3 4]
type(x):  <class 'numpy.ndarray'>
x.dtype:  int32
x.size:  4
x.shape:  (4,)


In [7]:
# Definir un arreglo 1D con elementos con tipo de dato de punto flotante

x = np.array([1,2,3,4], dtype=np.float32)
print(x)
print('type(x): ', type(x))
print('x.dtype: ', x.dtype)
print('x.size: ', x.size)
print('x.shape: ', x.shape)

[ 1.  2.  3.  4.]
type(x):  <class 'numpy.ndarray'>
x.dtype:  float32
x.size:  4
x.shape:  (4,)


In [8]:
# Sumar los arreglos x e y

y = np.array([5,6,7,8])
print('x: ', x)
print('y: ', y)
print('Suma: ', x+y)

x:  [ 1.  2.  3.  4.]
y:  [5 6 7 8]
Suma:  [  6.   8.  10.  12.]


In [9]:
# Definir un arreglo 2D

x= np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(type(x))
print(x.size)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
8
(2, 4)


### Slicing

In [20]:
x[1:]

array([[5, 6, 7, 8]])

In [11]:
x[1:2, 2:]

array([[7, 8]])

In [15]:
x[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

**Cómo funciona el slicing en los arreglos de Numpy**<br />
<img src="images/numpy_indexing.png" width="400">

In [21]:
# Inicializar un arreglo 1D y otro 2D con ceros. Notar que usamos Y por X

x=np.zeros(10)
print('x: ', x)

x:  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [22]:
y=np.zeros([2,4])
print(y)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [23]:
# Crear un arreglo usando valores aleatorios entre 0 y 1

x=np.random.random(20)
print(x)

[ 0.43239802  0.93681354  0.16603854  0.92811443  0.00816845  0.34307541
  0.81592701  0.60037483  0.04393727  0.90242068  0.01394602  0.16304797
  0.15778609  0.86834701  0.30982932  0.21438946  0.749361    0.80308996
  0.48324849  0.21600365]


In [24]:
# Extraer valores de un arreglo Numpy usando indices

x= np.array([[1,2,3,4],
            [5,6,7,8],
             [9,10,11,12]])
print(x)

print('\nx[0,3]: ', x[0,3])

print('\nx[:,0]: ', x[:,0])
print('\nx[0,:]: ', x[0,:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

x[0,3]:  4

x[:,0]:  [1 5 9]

x[0,:]:  [1 2 3 4]


In [25]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
# Numpy permite crear máscaras fácilmente usando condiciones booleanas
a=x>6
print(a)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [27]:
# Extraer los valores de x que satisfacen la condición booleana. Para ello usamos la máscara
print(x[a])

[ 7  8  9 10 11 12]


In [28]:
x.shape

(3, 4)

In [29]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
# Sumar los valores de un arreglo 2D a lo largo del eje Y (columnas)
np.sum(x, axis=0)

array([15, 18, 21, 24])

In [31]:
# Sumar los valores de un arrego 2D a lo largo del eje X (filas)
np.sum(x, axis=1)

array([10, 26, 42])

In [32]:
# Crear la transpuesta de la matriz x
y= x.T
print(y, y.shape)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]] (4, 3)


## Funciones matemáticas

In [33]:
x=np.random.random(1000)
#print(x)
print('Media: ', np.mean(x))
print('Desviación Estandar: ', np.std(x))

Media:  0.499484330111
Desviación Estandar:  0.289998085081


In [34]:
x=np.random.randn(1000)
print('Media: ', np.mean(x))
print('Desviación Estandar: ', np.std(x))

Media:  -0.0117846760321
Desviación Estandar:  0.993353451024


In [ ]:
np.random.randn()

In [35]:
?np.random.randn()

In [36]:
help(np.random.randn())

Help on float object:

class float(object)
 |  float(x) -> floating point number
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      float.__format__(format_spec) -> string
 |      
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getformat__(...) from builtins.type
 |      float.__getformat__(typestr) -> string
 |      
 |      You probably don't want to use thi

In [37]:
# También es posible importar algunas funciones directamente desde las librerías
# Para ello usamos la sintaxis from <nombre_libreria> import <nombre_funcion>
from numpy.random import random

In [38]:
random(100)

array([ 0.67640328,  0.44951355,  0.34291668,  0.25033612,  0.34643367,
        0.51436099,  0.22192698,  0.12706471,  0.87746053,  0.61662887,
        0.82048765,  0.36327651,  0.34893583,  0.84762762,  0.08962072,
        0.76257155,  0.96748126,  0.17318529,  0.00357534,  0.40980796,
        0.87806901,  0.51354722,  0.21587825,  0.75088731,  0.27390111,
        0.63838742,  0.29639444,  0.0246066 ,  0.52605291,  0.14221492,
        0.91616029,  0.62997424,  0.78127398,  0.76198652,  0.54285976,
        0.16492825,  0.41321422,  0.50541613,  0.36193215,  0.73323014,
        0.9466869 ,  0.2363294 ,  0.10655401,  0.42830417,  0.50096357,
        0.78829415,  0.13000336,  0.98822318,  0.38438257,  0.11436343,
        0.20584152,  0.35773022,  0.94551825,  0.98447736,  0.29187658,
        0.71883485,  0.28831021,  0.00361393,  0.54640613,  0.76644747,
        0.96574572,  0.95600314,  0.43796328,  0.35600548,  0.17757925,
        0.098954  ,  0.2089319 ,  0.84267863,  0.35547833,  0.57

In [39]:
# Crear un arreglo de enteros que comience en 0 y termine en 10 (no incluído)
x=np.arange(0,10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
# Crear un arreglo de punto flotante que comience en 0 y termine en 10, con paso de 0.5
x=np.arange(0,10,0.5, dtype=np.float64)
print(x)
print(x.dtype)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]
float64


In [41]:
# Usar funciones trigonométricas
# Numpy contiene una serie de constantes matemáticas. Usaremos Pi
print(x[3:8])
x_expo = np.exp(x[3:8])
x_log = np.log(x[3:8])
print(x_expo)
print(x_log)

[ 1.5  2.   2.5  3.   3.5]
[  4.48168907   7.3890561   12.18249396  20.08553692  33.11545196]
[ 0.40546511  0.69314718  0.91629073  1.09861229  1.25276297]


In [42]:
# Usar funciones como potencia
y=np.power(x,2) # elevar cada elemento del arreglo x, a la segunda potencia
print(y)

[  0.     0.25   1.     2.25   4.     6.25   9.    12.25  16.    20.25  25.
  30.25  36.    42.25  49.    56.25  64.    72.25  81.    90.25]


In [43]:
# Usar funciones como raíz cuadrada
y=np.sqrt(x) # raíz de a, del inglés "square root"
print(y)

[ 0.          0.70710678  1.          1.22474487  1.41421356  1.58113883
  1.73205081  1.87082869  2.          2.12132034  2.23606798  2.34520788
  2.44948974  2.54950976  2.64575131  2.73861279  2.82842712  2.91547595
  3.          3.082207  ]


Escribir *np.sqrt(x)* es mucho más breve que la alternativa de usar funciones nativas de Python: Calcular una a una las raíces cuadradas de cada elemento de *x*.